# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicaps.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('level_4', models.IntegerField()),
                ('level_4_result', models.DecimalField(decimal_places=1, max_digits=2)),
                ('level_3_min', models.IntegerField()),
                ('level_3_max', models.IntegerField()),
                ('level_3_result', models.DecimalField(decimal_places=1, max_digits=2)),
                ('level_2_min', models.IntegerField()),
                ('level_2_max', models.IntegerField()),
                ('level_2_result', models.DecimalField(decimal_places=1, max_digits=2)),
                ('level_1', models.IntegerField()),
                ('level_1_result', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_use', models.IntegerField(choices=[(3, '3 grades'), (4, '4 grades'), (5, '5 grades')], default=3)),
                ('grade_a_min', models.IntegerField(default=0)),
                ('grade_a_max', models.IntegerField(default=0)),
                ('grade_b_min', models.IntegerField(default=0)),
                ('grade_b_max', models.IntegerField(default=0)),
                ('grade_c_min', models.IntegerField(default=0)),
                ('grade_c_max', models.IntegerField(default=0)),
                ('grade_d_min', models.IntegerField(default=0)),
                ('grade_d_max', models.IntegerField(default=0)),
                ('grade_e_min', models.IntegerField(default=0)),
                ('grade_e_max', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('handicap', models.DecimalField(decimal_places=1, max_digits=3)),
                ('latest_handicap_change', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('latest_game', models.DateField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('handicap_rounded', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gamescore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicaps.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicaps.GameType'),
        ),
    ]
