# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicaps', '0001_initial_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='attendance',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
