# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicaps', '0002_add_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='handicap',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='handicap_change',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
