# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicaps', '0002_player_handicap_rounded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_use',
            field=models.IntegerField(choices=[(3, '3 grades'), (4, '4 grades'), (5, '5 grades')], default=3),
        ),
    ]
